version: '3.8'
#for local setup
services:
  db:
    image: mariadb:latest
    restart: always
    container_name: illuminati-db
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DBNAME}
      MARIADB_USER: ${DBUSER}
      MARIADB_PASSWORD: ${DBPASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 3
  backend:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000" 
    container_name: illuminati-backend
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
       db:
        condition: service_healthy
    environment:
        DBNAME: ${DBNAME}
        DBUSER: ${DBUSER}
        DBPASSWORD: ${DBPASSWORD}
        DBHOST: db
        DBPORT: 3306

  frontend:
    build:
      context: ../illuminati-app-frontend/ #eddit to corresponding local path
      dockerfile: Dockerfile
    container_name: illuminati-frontend
    ports:
      - '8080:8080'
    volumes:
      - ../illuminati-app-frontend/src:/app/src  #eddit to corresponding local path
      - ../illuminati-app-frontend/node_modules:/app/node_modules

  #go-scheduler:
  #  build: ./go-scheduler   
  #  restart: always
  #  depends_on:
  #    db:
  #      condition: service_healthy
  #  environment:
  #    DBNAME: ${DBNAME}
  #    DBUSER: ${DBUSER}
  #    DBPASSWORD: ${DBPASSWORD}
  #    DBHOST: db
  #    DBPORT: 3306
  #    SMTP_EMAIL: ${SMTP_EMAIL}
  #    SMTP_PASS: ${SMTP_PASS}

  
